
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { UserContext } from "@/context/UserContext";   // Provides user authentication and profile context
import Footer from "@/components/Footer";              
import Navbar from "@/components/Navbar";              

import { Toaster } from "sonner";
import Head from "next/head";

// Load and configure Geist Sans font
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name
  subsets: ["latin"],            // Subset to include only Latin characters
});

// Load and configure Geist Mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name
  subsets: ["latin"],
});

// Default metadata for the application
export const metadata = {
  title: "BusExpress",           // Default title for all pages
  description: "Generated by create next app", // Default meta description
};

// Root layout component which wraps the entire app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the app with global StateContext provider */}

        {/* Wrap with UserContext provider for managing user authentication and profile */}
        <UserContext>
         
            <div className="layout">
              {/* Set the document title via Head (local override for title if needed) */}
              <Head>
                <title>Dine Market</title>
              </Head>

              {/* Header section with navigation bar */}
              <header>
                <Navbar />
              </header>

              {/* Main content area where individual page components will be rendered */}
              <main className="main-container">
                {children}
              </main>

              {/* Footer section */}
              <footer>
                <Footer />
              </footer>

              {/* Global toaster for displaying notifications (errors, success, etc.) */}
              <Toaster
                richColors // Enable rich color notifications
                position="top-center" // Position the toasts at the top center
              />
            </div>
        </UserContext>
      </body>
    </html>
  );
}
